services:
  powersimdata:
    container_name: scenario_client
    hostname: scenario_client
    build:
      context: ../../PowerSimData
    env_file:
      - client.env
    image: ghcr.io/breakthrough-energy/powersimdata:latest
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - scenario_data:/mnt/bes/pcm
      - ./ssh:/root/.ssh
      - ./tests:/app/tests
  scenario_server:
    container_name: scenario_server
    hostname: scenario_server
    build:
      context: ..
      dockerfile: scenario_framework/Dockerfile
    image: scenario_server:latest
    tty: true
    volumes:
      - ./ssh/id_rsa.pub:/pub_key/id_rsa.pub:ro # path to ssh public key
    env_file:
      - server.env
    restart: "unless-stopped"
  # reisejl:
  #   container_name: reisejl
  #   hostname: reisejl
  #   build:
  #     context: ../../REISE.jl
  #   image: ghcr.io/breakthrough-energy/reisejl:latest
  #   volumes:
  #     - scenario_data:/mnt/bes/pcm
      # - ../gurobi_license:/usr/share/gurobi_license
volumes:
  scenario_data:
