version: '3.7'

services:
  powersimdata:
    container_name: scenario_client
    hostname: scenario_client
    build:
      context: ../../PowerSimData
    environment: 
      - BE_SERVER_USER=${BE_SERVER_USER:-foo}
      - BE_SERVER_ADDRESS=scenario_server
      - BE_SERVER_SSH_PORT=2222
    image: powersimdata:latest
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - scenario_data:/mnt/bes/pcm
      - $PWD/ssh:/root/.ssh
      - $PWD/tests:/app/tests
  scenario_server:
    container_name: scenario_server
    hostname: scenario_server
    build:
      context: ..
      dockerfile: scenario_framework/Dockerfile
    image: scenario_server:latest
    tty: true
    volumes:
      - $PWD/ssh/id_rsa.pub:/pub_key/id_rsa.pub:ro # path to ssh public key
    environment:
      - USER_NAME=${BE_SERVER_USER:-foo}
      - PUBLIC_KEY_FILE=/pub_key/id_rsa.pub # ssh public key in container
      - SUDO_ACCESS=false
      - PASSWORD_ACCESS=false
    restart: "unless-stopped"
  # reisejl:
  #   container_name: reisejl
  #   hostname: reisejl
  #   build:
  #     context: ../../REISE.jl
  #   image: reisejl:latest
  #   ports:
  #     - "80:5000"
  #   volumes:
  #     - scenario_data:/mnt/bes/pcm
  #     - ../gurobi.lic:/usr/share/gurobi_license/gurobi.lic
volumes:
  scenario_data:
