name: Publish docker image

on: 
  workflow_dispatch:
    inputs:
      imageTag:
        description: 'Tag to push'
        required: false
        default: 'latest'

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          context: build
          build-args: version=${{ github.event.inputs.imageTag }}
          tags: ghcr.io/breakthrough-energy/postreise:${{ github.event.inputs.imageTag }}
