name: Test client server

on:
  workflow_dispatch:

jobs:
  test:
    if: "!contains(github.event.head_commit.message, 'skip_ci')"

    runs-on: ubuntu-latest

    name: End to end tests
    steps:
      - uses: actions/checkout@v3

      - run: docker-compose build scenario_server
        working-directory: scenario_framework

      - name: Start containers
        run: |
          docker-compose up -d
          sleep 10
        working-directory: scenario_framework

      - run: docker exec scenario_client bash -c 'pytest -m "not db"'
