name: Integration

on: [workflow_dispatch]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip_ci')"

    runs-on: ubuntu-latest

    name: End to end tests
    steps:
      - name: Checkout plug
        uses: actions/checkout@v2
        with:
          path: plug

      - name: Checkout PowerSimData
        uses: actions/checkout@v2
        with:
          repository: Breakthrough-Energy/PowerSimData
          path: PowerSimData

      # - name: Checkout REISE.jl
      #   uses: actions/checkout@v2
      #   with:
      #     repository: Breakthrough-Energy/REISE.jl
      #     path: REISE.jl

      - run: docker-compose build
        working-directory: plug/scenario_framework

      - name: Start containers
        run: |
          docker-compose up -d
          sleep 10
        working-directory: plug/scenario_framework

      - run: docker exec scenario_client bash -c 'pytest -m "not db"'
